---
- name: Install nginx
  hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure nginx is enabled and running
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true
